---
title: "Data Processing"
author: "Ian Lo, Elaine Ye"
date: "12/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Bike Trip Data Summarized and Sampled
```{r}

library(tidyverse)
library(lubridate)

# 2020 Citi Bike data
bikedata <- list.files(pattern = "*-citibike-tripdata.csv") %>%
  map_df(~read_csv(.))

# clean up columns
colnames(bikedata) = c("trip_duration", "start_time","stop_time","start_station_id","start_station_name","start_station_latitude","start_station_longitude","end_station_id","end_station_name","end_station_latitude","end_station_longitude","bike_id","user_type","birth_year","gender")

# add trip_date based on start_time
bikedata$trip_date <- as.Date(bikedata$start_time)

# number of daily trips
bikedata_summarized <- bikedata %>% group_by(trip_date) %>% summarise(daily_trips = n())
bikedata_summarized_station <- bikedata %>% group_by(trip_date, start_station_name) %>% summarise(daily_trips = n())
write.csv(bikedata_summarized,"bikedata_summarized.csv", row.names = FALSE)

# sample X% of data per day
set.seed(260)

bikedata_sampled_10percent <- bikedata %>% group_by(trip_date) %>% sample_frac(0.1)
nrow(bikedata_sampled_10percent) #1,950,690
write.csv(bikedata_sampled_10percent,"bikedata_sampled_10percent.csv", row.names = FALSE)

bikedata_sampled_1percent <- bikedata %>% group_by(trip_date) %>% sample_frac(0.01)
nrow(bikedata_sampled_1percent) #195,064
write.csv(bikedata_sampled_1percent,"bikedata_sampled_1percent.csv", row.names = FALSE)


# 2019 Citi Bike data
bikedata2019 <- list.files(path = "2019", pattern = "*-citibike-tripdata.csv") %>%
  map_df(~read_csv(paste0("2019/",.)))

bikedata201908 <- read_csv("2019/201908-citibike-tripdata.csv")
bikedata2019_combined <- rbind(bikedata2019, bikedata201908)

colnames(bikedata2019_combined) = c("trip_duration", "start_time","stop_time","start_station_id","start_station_name","start_station_latitude","start_station_longitude","end_station_id","end_station_name","end_station_latitude","end_station_longitude","bike_id","user_type","birth_year","gender")

bikedata2019_combined$trip_date <- as.Date(bikedata2019_combined$start_time)
bikedata_summarized_2019 <- bikedata2019_combined %>% group_by(trip_date) %>% summarise(daily_trips = n())
write.csv(bikedata_summarized_2019,"bikedata_summarized_2019.csv", row.names = FALSE)

```


## Aggregate trip counts by station

```{r}
# start/end trips per station
startstations <- distinct(bikedata, start_station_id, .keep_all = TRUE) %>%
  select(start_station_id, start_station_name, start_station_longitude, start_station_latitude) %>%
  rename(station_id = start_station_id, station_name = start_station_name, station_longitude=start_station_longitude, station_latitude = start_station_latitude)

endstations <- distinct(bikedata, end_station_id, .keep_all = TRUE) %>%
  select(end_station_id, end_station_name, end_station_longitude, end_station_latitude) %>%
  rename(station_id = end_station_id, station_name = end_station_name, station_longitude=end_station_longitude, station_latitude = end_station_latitude)

station_lookup <- bind_rows(startstations, endstations) %>% distinct(station_id, .keep_all = TRUE)
write.csv(station_lookup,"bikestation_lookup.csv", row.names = FALSE)

# count daily trip starts for each station/date
daily_starts <- group_by(bikedata, trip_date, start_station_id) %>%
  summarize(startcount = n()) %>%
  rename(station_id = start_station_id)

# count daily trip ends for each station/date
daily_ends <- group_by(bikedata, trip_date, end_station_id) %>%
  summarize(endcount = n()) %>%
  rename(station_id = end_station_id)

# full join them so we don't lose any where there were starts but not ends and vice versa
combined <- full_join(daily_starts, daily_ends, by = c('trip_date', 'station_id'))
with_station_info <- left_join(combined, station_lookup, by='station_id')
write.csv(with_station_info,"bikestation_dailytrips.csv", row.names = FALSE)
```

## Subway Data

```{r}
library(stringr)

subway_sta <- read_csv("Data/DOITT_SUBWAY_STATION_01_13SEPT2010.csv")

#clean up geom point 
temp1 <- subway_sta %>%
  mutate(the_geom = str_remove(the_geom, "POINT")) %>%
  mutate(the_geom = str_remove(the_geom, " \\(")) %>%
  mutate(the_geom = str_remove(the_geom, "\\)")) 

x <- str_split(temp1$the_geom, " ", simplify = TRUE)
geom_sta <- as.data.frame(x) %>%
  rename(station_long = V1,
         station_lat = V2) %>%
  mutate(station_long = as.numeric(station_long),
         station_lat = as.numeric(station_lat))

subway_station <- cbind(temp1, geom_sta) %>%
  select(c(3,7,8))
```

```{r}
start_station <- read_csv("Data/bikestation_lookup.csv")
```

## Connecting Bike Stations to Nearby Subway Stations
```{r}
#the closet subway station for each bike start station
library(spatialrisk)
distance_subway <- purrr::map2_dfr(start_station$station_latitude, start_station$station_longitude, 
                  ~spatialrisk::points_in_circle(subway_station, .y, .x, 
                                                 lon = station_long, 
                                                 lat = station_lat, 
                                                 radius = 1e6)[1,], 
                .id = "id_bike")
start_station$id_bike <- 1:nrow(start_station) 
start_station$id_bike <- as.factor(start_station$id_bike)

library(ggmap)
library(tidygeocoder)
#get zipcode, city, suburb, state from https://nominatim.org/ 
#comment out after the first run- took a long time
start_geo <- start_station %>%
   reverse_geocode(lat = station_latitude, long = station_longitude, method = "osm", 
                  full_results = TRUE) 

#save(start_geo, file = "start_geo.Rdata")
start_geosub <- start_geo %>%
  select(id_bike, station_id, station_longitude, station_latitude, suburb, city, postcode) 

#make zipcode consistent and manually correct mistakes
start_geocode <- start_geosub %>%
  mutate(postcode = str_remove(postcode, "-[0-9]{0,4}")) %>%
  mutate(postcode = str_remove(postcode, ":[0-9]{0,4}")) %>%
  mutate(postcode = recode(postcode, 
                           "100" = "10019",
                           "112321" = "11231",
                           "104515" = "10451",
                           "100090" = "10009",
                           "100374" = "10037",
                           "100014" = "10014",
                           "100090" = "10009",
                           "100036" = "10036",
                           "11227" = "11217",
                           "10000" = "10007")) %>%
  mutate(postcode = ifelse(station_id == 367, "10022", 
                           ifelse(station_id == 3443, "10019",
                                  ifelse(station_id == 3263, "10003", postcode))))

library(zipcodeR)
#get census data from zipcode 
nyctract <- reverse_zipcode(start_geocode$postcode) %>%
  select(zipcode, major_city, county, population_density, median_household_income)

start_census <- start_geocode %>%
  left_join(nyctract, by = c("postcode" = "zipcode"))
```

```{r}
#join closet subway station to start_station data 
start_subway <- start_census %>%
  left_join(distance_subway, by = "id_bike") %>%
  select(-c(station_longitude, station_latitude, 
            id_bike, station_long, station_lat))
#join distance and geocode back to bike data 
bike_join <- start_station %>%
  left_join(start_subway, by = "station_id") %>%
  rename(subway_name = NAME) %>%
  mutate(trip_min = trip_duration/60) 
#subset of sample, create distance 
save(bike_join, file = "bike_join.RData")
```


Reference: 
https://ny.curbed.com/2019/7/10/20689177/citi-bike-equity-expansion-report
https://github.com/jessecambon/tidygeocoder 
https://nominatim.org/
https://data.cityofnewyork.us/Transportation/Subway-Stations/arq3-7z49
https://stackoverflow.com/questions/57525670/find-closest-points-lat-lon-from-one-data-set-to-a-second-data-set
