---
title: "EDA_Ye"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
bikedata <- list.files(pattern = "*-citibike-tripdata.csv") %>% 
  map_df(~read_csv(.))

# NYC Covid Data: https://github.com/nychealth/coronavirus-data/tree/master/trends
coviddata <- read_csv("COVIDcasedata.csv")

# NYC Weather Data: New York, NY 10023 https://www.ncdc.noaa.gov/cdo-web/datasets/GHCND/locations/ZIP:10023/detail
weatherdata <- read_csv("NYCWeather.csv") %>%
  select(DATE, AWND, PRCP, SNOW, SNWD, TMAX, TMIN)

# clean up column names
colnames(bikedata) = c("trip_duration", "start_time","stop_time","start_station_id","start_station_name","start_station_latitude","start_station_longitude","end_station_id","end_station_name","end_station_latitude","end_station_longitude","bike_id","user_type","birth_year","gender")

# add trip_date based on start_time
bikedata$trip_date <- as.Date(bikedata$start_time)
```

```{r}
#set.seed(260)
#bikedata_1 <- sample_frac(bikedata, 0.01)
```

```{r}
library(lubridate)
bikedata <- bikedata %>%
  mutate(age = 2020 - birth_year) %>%
  mutate(day_of_week = wday(start_time, label = TRUE, abbr = TRUE))

bike_weather <- bikedata %>%
  left_join(weatherdata, by = c("trip_date" = "DATE"))
```

```{r}
bike_weather %>%
  mutate(month = month(trip_date)) %>%
  group_by(month, day_of_week) %>%
  summarize(wday_trips = n()) %>%
  ggplot(aes(x = day_of_week, y = wday_trips, group = 1), data = .) +
  geom_point(color = "#379DDA") +
  geom_line(color = "#379DDA", size = 0.5) +
  facet_wrap(.~month) +
  scale_y_continuous(labels = scales::comma) +
  labs(title = "Citi Bike Trips by Day of Week per Month in 2020",
       x = "", y = "number of trips") +
  theme_light() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank())
head(bike_weather)
```

